export interface Sucursal {
  id: string,
  titulo: string,
  ubicacion: string,
  departamento: string,
  ciudad: string,
  direccion: string,
  telefono_primario: string,
  telefono_secundario: string,
  telefono_terciario: string,
  celular_primario: string,
  celular_secundario: string,
  celular_terciario: string,
  horario: string,
  latitud: string,
  longitud: string,
  imagen_primaria: string,
  imagen_secundaria: string,
  imagen_terciaria: string,
  detalles: string,
  descripcion: string,
  correo: string,
  encargado: string,
  referencia: string,
  tipo: string
}